"""Home Assistant core's own USB discovery matcher table, vendored.

Source: https://github.com/home-assistant/core/blob/2026.8.2/homeassistant/generated/usb.py
Pinned ref: 2026.8.2 (the latest stable release tag at generation time -- never `dev`)
Fetched: 2026-08-17
License: Apache License 2.0 (https://github.com/home-assistant/core/blob/2026.8.2/LICENSE.md)
  Copyright the Home Assistant Authors. This file is a derived, mechanical
  extraction of upstream's own generated/usb.py -- not a copy of any of HA's
  original source code -- reproduced here under the same license.

Generated by tools/generate_usb_matchers.py -- do not hand-edit. Re-run that
script to pick up whatever the current latest release contains.
"""

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class UsbMatcher:
    """One entry from HA's own USBMatcher TypedDict (homeassistant/loader.py)."""

    domain: str
    vid: str | None = None
    pid: str | None = None
    description: str | None = None
    manufacturer: str | None = None
    serial_number: str | None = None


USB_MATCHERS: tuple[UsbMatcher, ...] = (
    UsbMatcher(
        domain="enocean", vid="0403", pid="6001", description="*usb 300*", manufacturer="*enocean*"
    ),
    UsbMatcher(domain="homeassistant_connect_zbt2", vid="303A", pid="4001", description="*zbt-2*"),
    UsbMatcher(domain="homeassistant_connect_zbt2", vid="303A", pid="831A", description="*zbt-2*"),
    UsbMatcher(
        domain="homeassistant_sky_connect", vid="10C4", pid="EA60", description="*skyconnect v1.0*"
    ),
    UsbMatcher(
        domain="homeassistant_sky_connect",
        vid="10C4",
        pid="EA60",
        description="*home assistant connect zbt-1*",
    ),
    UsbMatcher(domain="insteon", vid="10BF"),
    UsbMatcher(domain="modem_callerid", vid="0572", pid="1340"),
    UsbMatcher(
        domain="rainforest_raven",
        vid="0403",
        pid="8A28",
        description="*raven*",
        manufacturer="*rainforest*",
    ),
    UsbMatcher(
        domain="rainforest_raven",
        vid="04B4",
        pid="0003",
        description="*emu-2*",
        manufacturer="*rainforest*",
    ),
    UsbMatcher(domain="velbus", vid="10CF", pid="0B1B"),
    UsbMatcher(domain="velbus", vid="10CF", pid="0516"),
    UsbMatcher(domain="velbus", vid="10CF", pid="0517"),
    UsbMatcher(domain="velbus", vid="10CF", pid="0518"),
    UsbMatcher(domain="zha", vid="10C4", pid="EA60", description="*2652*"),
    UsbMatcher(domain="zha", vid="10C4", pid="EA60", description="*slzb-07*"),
    UsbMatcher(domain="zha", vid="1A86", pid="55D4", description="*sonoff*plus*"),
    UsbMatcher(domain="zha", vid="10C4", pid="EA60", description="*sonoff*plus*"),
    UsbMatcher(domain="zha", vid="10C4", pid="EA60", description="*tubeszb*"),
    UsbMatcher(domain="zha", vid="1A86", pid="7523", description="*tubeszb*"),
    UsbMatcher(domain="zha", vid="1A86", pid="7523", description="*zigstar*"),
    UsbMatcher(domain="zha", vid="1CF1", pid="0030", description="*conbee*"),
    UsbMatcher(domain="zha", vid="0403", pid="6015", description="*conbee*"),
    UsbMatcher(domain="zha", vid="10C4", pid="8A2A", description="*zigbee*"),
    UsbMatcher(domain="zha", vid="0403", pid="6015", description="*zigate*"),
    UsbMatcher(domain="zha", vid="10C4", pid="EA60", description="*zigate*"),
    UsbMatcher(domain="zha", vid="10C4", pid="8B34", description="*bv 2010/10*"),
    UsbMatcher(domain="zha", vid="10C4", pid="EA60", description="*sonoff*max*"),
    UsbMatcher(domain="zha", vid="10C4", pid="EA60", description="*sonoff*lite*mg21*"),
    UsbMatcher(domain="zwave_js", vid="0658", pid="0200"),
    UsbMatcher(domain="zwave_js", vid="10C4", pid="8A2A", description="*z-wave*"),
    UsbMatcher(
        domain="zwave_js",
        vid="303A",
        pid="4001",
        description="*nabu casa zwa-2*",
        manufacturer="nabu casa",
    ),
    UsbMatcher(
        domain="zwave_js",
        vid="10C4",
        pid="EA60",
        description="*sonoff*zwave*",
        manufacturer="sonoff",
    ),
)
